---
- name: Deploy to Tomcat
  hosts: web
  become: yes

  tasks:

    - name: Copy WAR file to Tomcat
      copy:
        src: "{{ lookup('env','WORKSPACE') }}/target/finalinternal.war"
        dest: /opt/tomcat/webapps/finalinternal.war

    - name: Restart Tomcat
      shell: |
        /opt/tomcat/bin/shutdown.sh || true
        sleep 5
        /opt/tomcat/bin/startup.sh
