---
- name: Deploy to Tomcat
  hosts: web
  become: yes

  tasks:

    - name: Copy WAR file
      copy:
        src: /var/snap/jenkins/5022/workspace/finalinternal/target/finalinternal.war
        dest: /var/lib/tomcat9/webapps/finalinternal.war
        remote_src: no

    - name: Restart Tomcat
      service:
        name: tomcat9
        state: restarted
