---
- name: Deploy to Tomcat
  hosts: web
  become: yes

  tasks:

    - name: Copy WAR file to Tomcat
      copy:
        src: "{{ lookup('env','WORKSPACE') }}/target/finalinternal.war"
        dest: /var/lib/tomcat9/webapps/finalinternal.war

    - name: Restart Tomcat
      service:
        name: tomcat9
        state: restarted
